---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ember-csi-aio-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: io.ember-csi.external-ceph-sc
